name: ogbench
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - comm=0.2.2
  - debugpy=1.6.7
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.15
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.10.15
  - python-dateutil=2.9.0
  - python_abi=3.10
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - chex==0.1.87
      - click==8.1.7
      - cloudpickle==3.1.0
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==4.4.2
      - distrax==0.1.5
      - dm-control==1.0.24
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.10.0
      - farama-notifications==0.0.4
      - flax==0.10.0
      - fonttools==4.54.1
      - fsspec==2024.10.0
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - gymnasium==1.0.0
      - humanize==4.11.0
      - idna==3.10
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - jax==0.4.35
      - jax-cuda12-pjrt==0.4.35
      - jax-cuda12-plugin==0.4.35
      - jaxlib==0.4.34
      - kiwisolver==1.4.7
      - labmaze==1.0.6
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.5.0
      - moviepy==1.0.3
      - msgpack==1.1.0
      - mujoco==3.2.4
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.6.3.3
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvcc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvjitlink-cu12==12.6.77
      - ogbench==1.0.1
      - opt-einsum==3.4.0
      - optax==0.2.3
      - orbax-checkpoint==0.7.0
      - pillow==11.0.0
      - proglog==0.1.10
      - protobuf==5.28.3
      - pyopengl==3.1.7
      - pyparsing==3.2.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==13.9.3
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - tensorflow-probability==0.24.0
      - tensorstore==0.1.67
      - toolz==1.0.0
      - tqdm==4.66.5
      - urllib3==2.2.3
      - wandb==0.18.5
      - zipp==3.20.2